import type { Metadata, Viewport } from "next";
import localFont from "next/font/local";
import { Geist, Geist_Mono, Inter } from "next/font/google";
import "./globals.css";
import { cn } from "@/lib/utils";
import { Providers } from "@/components/providers";
import PreventZoom from "@/components/prevent-zoom";

const inter = Inter({ subsets: ["latin"], variable: "--font-sans" });

const zarathustra = localFont({
  src: "./fonts/Zarathustra.otf",
  variable: "--font-serif",
  display: "swap",
});

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export const viewport: Viewport = {
  width: "device-width",
  initialScale: 1,
  maximumScale: 1,
  userScalable: false,
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={cn(
        "h-full",
        "antialiased",
        geistSans.variable,
        geistMono.variable,
        zarathustra.variable,
        "font-serif",
        inter.variable,
      )}
    >
      <body
        className="flex h-svh overflow-hidden font-sans"
        suppressHydrationWarning
      >
        <PreventZoom />
        <Providers>{children}</Providers>
      </body>
    </html>
  );
}
